// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChitChat_ServerStream_FullMethodName = "/ChitChat/ServerStream"
)

// ChitChatClient is the client API for ChitChat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Maintain rpc calls between server and client.
type ChitChatClient interface {
	ServerStream(ctx context.Context, in *Chat_Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatMsg], error)
}

type chitChatClient struct {
	cc grpc.ClientConnInterface
}

func NewChitChatClient(cc grpc.ClientConnInterface) ChitChatClient {
	return &chitChatClient{cc}
}

func (c *chitChatClient) ServerStream(ctx context.Context, in *Chat_Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChitChat_ServiceDesc.Streams[0], ChitChat_ServerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Chat_Request, ChatMsg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChitChat_ServerStreamClient = grpc.ServerStreamingClient[ChatMsg]

// ChitChatServer is the server API for ChitChat service.
// All implementations must embed UnimplementedChitChatServer
// for forward compatibility.
//
// Maintain rpc calls between server and client.
type ChitChatServer interface {
	ServerStream(*Chat_Request, grpc.ServerStreamingServer[ChatMsg]) error
	mustEmbedUnimplementedChitChatServer()
}

// UnimplementedChitChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChitChatServer struct{}

func (UnimplementedChitChatServer) ServerStream(*Chat_Request, grpc.ServerStreamingServer[ChatMsg]) error {
	return status.Errorf(codes.Unimplemented, "method ServerStream not implemented")
}
func (UnimplementedChitChatServer) mustEmbedUnimplementedChitChatServer() {}
func (UnimplementedChitChatServer) testEmbeddedByValue()                  {}

// UnsafeChitChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChitChatServer will
// result in compilation errors.
type UnsafeChitChatServer interface {
	mustEmbedUnimplementedChitChatServer()
}

func RegisterChitChatServer(s grpc.ServiceRegistrar, srv ChitChatServer) {
	// If the following call pancis, it indicates UnimplementedChitChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChitChat_ServiceDesc, srv)
}

func _ChitChat_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Chat_Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChitChatServer).ServerStream(m, &grpc.GenericServerStream[Chat_Request, ChatMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChitChat_ServerStreamServer = grpc.ServerStreamingServer[ChatMsg]

// ChitChat_ServiceDesc is the grpc.ServiceDesc for ChitChat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChitChat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ChitChat",
	HandlerType: (*ChitChatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStream",
			Handler:       _ChitChat_ServerStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto.proto",
}
